[package]
name = "libevent"
version = "0.0.0"
authors = ["Jon Magnuson <jon.magnuson@gmail.com>"]
description = "Rust bindings to the libevent async I/O framework"
repository = "https://github.com/jmagnuson/libevent-rs"
license = "MIT/Apache-2.0"
edition = "2018"

[workspace]
members = ['examples/hello']

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "openssl", "threading" ]
static = [ "libevent-sys/static" ]
bundled = [ "static", "libevent-sys/bundled" ]
openssl = [ "libevent-sys/openssl" ]
openssl_bundled = [ "libevent-sys/openssl_bundled", "threading" ]
threading = [ "libevent-sys/threading" ]

[dependencies]
bitflags = "1.2"
libevent-sys = { version = "0.2", path = "libevent-sys" }
