[package]
name = "hello"
version = "0.1.0"
authors = ["Jon Magnuson <jon.magnuson@gmail.com>"]
edition = "2018"

[dependencies]
libevent-sys = { path = "../../libevent-sys" }
libevent = { path = "../../" }

[build-dependencies]
cmake = "0.1"
